# Recorrido por N nodos

In [39]:
from Grafo import Grafo
import numpy as np

# armo un grafo
grafito = Grafo()
lista_vertices = ["A","B","C","D","E","F","G"]
lista_aristas = [("A","B"), ("B","C"), ("C","D"), ("D","E"), ("B","E"),("C","E")]

for k in lista_vertices:
    grafito.agregar_vertice(k)

for a,b in lista_aristas:
    grafito.agregar_arista(a,b, no_dirigido=True)

print(grafito)

{'A': 0, 'B': 1, 'C': 2, 'D': 3, 'E': 4, 'F': 5, 'G': 6}
<vertices: ['A', 'B', 'C', 'D', 'E', 'F', 'G']
 Adyacencias:
[[0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 0.]
 [0. 1. 0. 1. 1. 0. 0.]
 [0. 0. 1. 0. 1. 0. 0.]
 [0. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]] >


In [40]:
#self = grafito
def nnodos(origen, destino, largo):
    ruta = []
    
    # declaro funcion wrappeada
    def _nnodos(origen, destino, largo, ruta=[]):
        ruta.append(origen)
        if largo==0:
            if origen==destino:
                return True
            else:
                ruta.pop()
                return False


        for v in grafito.obtener_adyacentes(origen):
            if not v in ruta:
                if _nnodos(v, destino, largo-1, ruta):
                    return True

        ruta.pop()
        return False
    
    # inicio recursion
    _nnodos(origen, destino, largo, ruta)
    return ruta

In [44]:
print(nnodos("A", "B", 1))
print(nnodos("A", "E", 2))
print(nnodos("A", "E", 3))
print(nnodos("A", "E", 4))
print(nnodos("A", "E", 5))
print(nnodos("A", "E", 6))

['A', 'B']
['A', 'B', 'E']
['A', 'B', 'C', 'E']
['A', 'B', 'C', 'D', 'E']
[]
[]


In [42]:
a=[]
a.append("x")
a.append("y")
print(a)
a.pop()

print(a)

['x', 'y']
['x']
