In [1]:
from Grafo import Grafo
import numpy as np

grafito = Grafo()

lista_vertices = ["A","B","C","D","BA","BB"]
# aristas no dirigidas
lista_aristas = [("A","B",1), ("A","C",1), ("A","D",1), ("B","BA",1), ("B","BB",1),("BB","C",0.1)]

for k in lista_vertices:
    grafito.agregar_vertice(k)

for a,b,peso in lista_aristas:
    grafito.agregar_arista(a,b,peso=peso, no_dirigido=True)

    
d,p = grafito.camino_minimo(origen="A")

print(d)
print(p)
pila=[]

def imprimir_camino_minimo(d,p,pila, origen, dest=None):
    
    if dest==origen:
        pila.insert(0,dest)
        for element in pila:
            print(element,"->")
        pila.clear()
        return
    
    if dest==None:
        valor_min=0
        for clave,valor in d.items():
            if valor>valor_min:
                valor_min=valor
                dest=clave
    
    pila.insert(0,dest)
    imprimir_camino_minimo(d,p,pila, origen, p[dest])

{'A': 0, 'B': 1.0, 'C': 1.0, 'D': 1.0, 'BA': 2.0, 'BB': 1.1000000000000001}
{'A': None, 'B': 'A', 'C': 'A', 'D': 'A', 'BA': 'B', 'BB': 'C'}


In [2]:
grafito.centralidad()

{'A': 8, 'B': 8, 'BA': 0, 'BB': 4, 'C': 4, 'D': 0}

In [3]:
from numpy import random

cantidad_iteraciones=100
#Para obtener el pagerank de cada pagina necesitamos: 

#La matriz de adyacencias tiene pesos, se que tan fuerte es la union entre nodos y como se conectan,
#lo que hago es transponer la matriz y luego llevar sus columnas a que tengan como suma probabilidad=1,
#dado que Pagerank(A)=sum Pagerank(i)/L(i) con L(i)= cantidad de links en las paginas.
# Debe ser una matriz estocastica por eso se piden estas condiciones,
#una matriz estocastica cuenta con esta caracteristica.
M1=grafito.mat_adyacencias()
M=grafito.mat_adyacencias().transpose()
M/= M.sum(axis=0)
d=0.8 #duping factor, sino se queda oscilando entre links
M= d*M + (1-d)/len(grafito)

#Me genero un vector aleatorio (o sea un vector que tiene valores entre 0 y 1)
x=np.random.rand(len(grafito))

print("el vector x es:")
print(x)
#Sabemos que dado un vector v, lim n->oo A^k*v converge a sum lambda_i^k*v, con lambda_i cada ava.
#Con lo cual convergera a los aves de la matriz A.
#En este caso serán M y x nuestra matriz y vector.
for k in range (0,cantidad_iteraciones):
    y=M@x
    print(f"iteracion numero {k}")
    y/=y.sum()
    y_array=np.squeeze(np.asarray(y))
    print(y_array)
    
    if(np.linalg.norm(x-y_array)<0.01):
        break
    
    else:
        x=y_array+(np.random.rand()/10)**k
        
        
print("mi y resultante dps del for es:")        
print (x)

{'A': 0, 'B': 1, 'C': 2, 'D': 3, 'BA': 4, 'BB': 5}
{'A': 0, 'B': 1, 'C': 2, 'D': 3, 'BA': 4, 'BB': 5}
el vector x es:
[ 0.55941489  0.03630022  0.82962741  0.67212732  0.31958203  0.64651016]
iteracion numero 0
[ 0.4089573   0.31895906  0.0973752   0.0820274   0.03649307  0.05618797]
iteracion numero 1
[ 0.32125268  0.31519806  0.09798128  0.0870079   0.08357939  0.09498069]
iteracion numero 2
[ 0.27260945  0.26994066  0.11892842  0.11101016  0.10970856  0.11780275]
iteracion numero 3
[ 0.28272557  0.28162408  0.11359042  0.10487816  0.10419548  0.11298627]
iteracion numero 4
[ 0.27507441  0.27438415  0.11688387  0.10865801  0.10836493  0.11663463]
iteracion numero 5
[ 0.27843533  0.27820367  0.11516901  0.10668649  0.10650242  0.11500307]
mi y resultante dps del for es:
[ 0.27507451  0.27438425  0.11688397  0.1086581   0.10836503  0.11663473]


In [4]:
m,j = grafito.camino_minimo(origen="A",dest="B")

In [5]:
def camino(param,origen,destino=None): #recibira archivo y como lo quiero recorrer al mapa, desde donde y a donde
    grafo= Grafo()
    grafo.armar_grafo(param)
    
    distancia,predecesores=camino_minimo(grafo,origen,destino)
    imprimir_camino(distancia,predecesores)
    
#si llamo a mas barato se lo paso por parametro, si es con mas rapido tmb, pasa por CLO esto. 
# Ademas si no le paso dest pasandole mas rapido me obtiene el recorrido de forma optima x el mundo. 
#El de menos escalas es lo mismo pero en vez de eso lo haces con prim en lugar de camino_minimo,
#ver de puntero a funcion o algo asi

In [6]:
imprimir_camino_minimo(d,p,pila,"A","BB")


A ->
C ->
BB ->


In [7]:
imprimir_camino_minimo(d,p,pila,"A","BA")

A ->
B ->
BA ->
