In [1]:
from Grafo import Grafo
import numpy as np

grafito = Grafo()

lista_vertices = ["A","B","C","D","BA","BB"]
# aristas no dirigidas
lista_aristas = [("A","B",1), ("A","C",1), ("A","D",1), ("B","BA",1), ("B","BB",1),("BB","C",0.1)]

for k in lista_vertices:
    grafito.agregar_vertice(k)

for a,b,peso in lista_aristas:
    grafito.agregar_arista(a,b,peso=peso, no_dirigido=True)

    
d,p = grafito.camino_minimo(origen="A")


In [2]:
grafito.centralidad()

{'A': 8, 'B': 8, 'BA': 0, 'BB': 4, 'C': 4, 'D': 0}

In [26]:
from numpy import random

cantidad_iteraciones=100
#Para obtener el pagerank de cada pagina necesitamos: 

#La matriz de adyacencias tiene pesos, se que tan fuerte es la union entre nodos y como se conectan,
#lo que hago es transponer la matriz y luego llevar sus columnas a que tengan como suma probabilidad=1,
#dado que Pagerank(A)=sum Pagerank(i)/L(i) con L(i)= cantidad de links en las paginas.
# Debe ser una matriz estocastica por eso se piden estas condiciones,
#una matriz estocastica cuenta con esta caracteristica.
M1=grafito.mat_adyacencias()
print(M1.todense())
M=grafito.mat_adyacencias().transpose()
M/= M.sum(axis=0)
#Me genero un vector aleatorio (o sea un vector que tiene valores entre 0 y 1)
x=np.random.rand(len(grafito))

print("el vector x es:")
print(x)
#Sabemos que dado un vector v, lim n->oo A^k*v converge a sum lambda_i^k*v, con lambda_i cada ava.
#Con lo cual convergera a los aves de la matriz A.
#En este caso serán M y x nuestra matriz y vector.
for k in range (0,cantidad_iteraciones):
    y=M@x
    print(f"iteracion numero {k}")
    y/=y.sum()
    print(y)
    if((x-y).max()<0.01):
        x=y
        break
        
print("mi y resultante dps del for es:")        
print (y)

{'A': 0, 'B': 1, 'C': 2, 'D': 3, 'BA': 4, 'BB': 5}
[[ 0.   1.   1.   1.   0.   0. ]
 [ 1.   0.   0.   0.   1.   1. ]
 [ 1.   0.   0.   0.   0.   0.1]
 [ 1.   0.   0.   0.   0.   0. ]
 [ 0.   1.   0.   0.   0.   0. ]
 [ 0.   1.   0.1  0.   0.   0. ]]
{'A': 0, 'B': 1, 'C': 2, 'D': 3, 'BA': 4, 'BB': 5}
el vector x es:
[ 0.63530465  0.60051163  0.22443756  0.86445023  0.44967877  0.84146669]
iteracion numero 0
[[ 0.35085943  0.39449006  0.07972267  0.05856666  0.0553592   0.06100197]]
iteracion numero 1
[[ 0.35085943  0.39449006  0.07972267  0.05856666  0.0553592   0.06100197]]
iteracion numero 2
[[ 0.35085943  0.39449006  0.07972267  0.05856666  0.0553592   0.06100197]]
iteracion numero 3
[[ 0.35085943  0.39449006  0.07972267  0.05856666  0.0553592   0.06100197]]
iteracion numero 4
[[ 0.35085943  0.39449006  0.07972267  0.05856666  0.0553592   0.06100197]]
iteracion numero 5
[[ 0.35085943  0.39449006  0.07972267  0.05856666  0.0553592   0.06100197]]
iteracion numero 6
[[ 0.35085943  0.394