In [23]:
from Grafo import Grafo

grafito = Grafo()

grafito.agregar_nodo("CORDOBA")
grafito.agregar_nodo("BUENOS AIRES")
grafito.agregar_nodo("SALTA")
grafito.agregar_arista("CORDOBA","BUENOS AIRES",3)
print(grafito)


{'CORDOBA': 0, 'BUENOS AIRES': 1, 'SALTA': 2}
<Nodos: ['CORDOBA', 'BUENOS AIRES', 'SALTA']
 Adyacencias:
[[ 0.  3.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]] >


In [24]:
grafito._indices.items()

dict_items([('CORDOBA', 0), ('BUENOS AIRES', 1), ('SALTA', 2)])

In [25]:
indices = (np.where(grafito._mat_ady[0,:].todense()!=0))[1]
[nombre for nombre,idx in grafito._indices.items() if idx in indices]


['BUENOS AIRES']

In [26]:
grafito.lista_nodos()

['CORDOBA', 'BUENOS AIRES', 'SALTA']

In [27]:
m={"pepe":1, "gaston":4}
m["gaston"]

4

In [30]:
m["popo"]=float("Inf")

In [31]:
m

{'gaston': 4, 'pepe': 1, 'popo': inf}

In [20]:
list(m.values())

[1, 4, -1]

In [ ]:
0.0==0

In [28]:
ts=grafito._mat_ady[:,0]

In [29]:
ts

<3x1 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in Dictionary Of Keys format>

In [ ]:
grafito._mat_ady[:,0]=0

In [ ]:
grafito._mat_ady.todense()

In [ ]:
li=[1,9,3,4]
del li[0]
li.remove(9)
li

In [ ]:
li.index(4)

In [ ]:
li.extend([10,11])

In [ ]:
11 in li

In [ ]:
pepe = {"vero": "poshito rosa", "nando": 2, "poshito": 3}

In [ ]:
valid_dict = {(1,2,3):[1,2,3]} 
valid_dict #debe ser inmutable

In [ ]:
list(pepe.keys())

In [ ]:
list(pepe.values())

In [ ]:
"vero" in pepe

In [ ]:
pepe.get("vero")

In [ ]:
pepe.update({"cone":"comida"})

In [ ]:
pepe

In [ ]:
pepe

In [ ]:
pepe["platano"] = "s1 sen10r"

In [ ]:
pepe

In [ ]:
del pepe["platano"]

In [ ]:
pepe

In [ ]:
primer_set={2,3}
other_set = {3, 4, 5, 6}
primer_set & other_set  # da solo {3}
primer_set | other_set #es la union sin dos veces la interseccion digamos
primer_set - other_set #este hace algo raro, saca los elementos de la primera que esten en la segunda

In [ ]:
{1, 2, 3, 4} ^ {2, 3, 5} #este dice cuales son distintos entre ambos

In [ ]:
# Check if set on the left is a subset of set on the right
{1, 2} <= {1, 2, 3} #chequea si lo primero es un subespacio generado 
#por el segundo, con el piquito para el otro lado chequea si el de la derecha lo es

In [ ]:
2 in primer_set

In [ ]:
for animal in ["dog", "cat", "mouse"]:
    print("{} is a mammal".format(animal))

In [ ]:
for i in range(4): #empieza en 0, exclusivo a derecha
    print(i)


In [ ]:
for i in range(4, 17, 2):
    print(i)

In [ ]:

grafito2 = Grafo()

grafito2.agregar_nodo("pepe")

In [46]:
import heapq
heap = [(5,"buenos aires"),(2,"mendoza"),(3,"cancun"),(7,"venecia"),(2,"polonia"),(20,"turquia"),(1,"israel")]
heapq.heapify(heap)
print(heap)
heapq.heappush(heap,(27,"holanda"))
heapq.heapify(heap)
print(heap)

[(1, 'israel'), (2, 'mendoza'), (3, 'cancun'), (7, 'venecia'), (2, 'polonia'), (20, 'turquia'), (5, 'buenos aires')]
[(1, 'israel'), (2, 'mendoza'), (3, 'cancun'), (7, 'venecia'), (2, 'polonia'), (20, 'turquia'), (5, 'buenos aires'), (27, 'holanda')]


In [42]:
class Nodo_heap(object):
    def __init__(self,dato):
        self.dato = dato
    def obtener_valor():
        return dato
    def __lt__(self, other):
        return self.dato>other.dato
    def __gt__(self, other):
        return self.dato<other.dato
    def __eq__(self, other):
        return self.dato==other.dato
    def __str__(self):
        return str(self.dato)
    def __repr__(self):
        return str(self.dato)

heap = [Nodo_heap((1,"buenos aires")),Nodo_heap((7,"mendoza")),Nodo_heap((3,"cancun")),Nodo_heap((7,"venecia")),Nodo_heap((2,"polonia")),Nodo_heap((20,"turquia")),Nodo_heap((1,"israel"))]

heapq.heapify(heap)
print(heap)

[(20, 'turquia'), (7, 'venecia'), (3, 'cancun'), (7, 'mendoza'), (2, 'polonia'), (1, 'buenos aires'), (1, 'israel')]


In [43]:
yes=(5,6)
[vertice,distancia]=yes

In [44]:
vertice

5

In [45]:
yes

(5, 6)